baseUrl: https://www.random.org/strings/?num={num}&len={len}&unique={unique}&format={format}&rnd={rnd}&digits={digits}

# move to secrets.
jwt:
  secret: $2y$10$g:8xgfCa5qox7YcUNgzP0


logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:default
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always